### ISSUE TITLE
req doesnt work

### ISSUE THREAD

**Issue by stunna2k** [natrixdev/instagram-botter#5]
When i go in cmd, and paste "color a 
title Installing packages for instagram botter ...
cls
pip install instabot os version github owner instas instagram proxies colorama" everything works except the os it says "ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os" I have the newest version of python. 
![Screenshot 2023-07-04 152553](https://github.com/natrixdev/instagram-botter/assets/138619942/d09b1818-4df5-4a10-b7f4-196582f15c34)

**Comment by natrixdev** [comment]
I see
